#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 Peruri
# SPDX-License-Identifier: Apache-2.0
#
# gen_vectors.py — Generate test vectors for SHA-256 accelerator testbench
# Output: tb/vectors/vectors.hex (dan summary)

import hashlib
import struct
import os
import random

OUT_DIR = os.path.join(os.path.dirname(__file__), '..', 'tb', 'vectors')
os.makedirs(OUT_DIR, exist_ok=True)

def sha256hex(msg):
    return hashlib.sha256(msg).hexdigest()

def to_words(block_bytes):
    """Convert 64-byte block to 16 big-endian uint32."""
    return list(struct.unpack('>16I', block_bytes))

def pad_message(msg):
    """Standard SHA-256 padding, returns list of 64-byte blocks."""
    bit_len = len(msg) * 8
    msg = bytearray(msg)
    msg.append(0x80)
    while len(msg) % 64 != 56:
        msg.append(0x00)
    msg += struct.pack('>Q', bit_len)
    blocks = []
    for i in range(0, len(msg), 64):
        blocks.append(bytes(msg[i:i+64]))
    return blocks

def write_vector(f, label, msg, mode=1):
    digest = sha256hex(msg)
    assert len(digest) == 64, f"Digest length wrong for {label}"
    f.write(f"# {label} | len={len(msg)} | mode={mode}\n")
    f.write(f"# digest: {digest}\n")
    if mode == 0:
        blocks = pad_message(msg)
        f.write(f"# nblocks: {len(blocks)}\n")
        for i, blk in enumerate(blocks):
            words = to_words(blk)
            f.write(f"# block {i}: " + " ".join(f"{w:08x}" for w in words) + "\n")
    else:
        # Mode 1: raw message bytes as hex groups of 4
        f.write(f"# msg_hex: {msg.hex()}\n")
    f.write("\n")

# Main vector file
with open(os.path.join(OUT_DIR, 'vectors.hex'), 'w') as f:
    f.write("# SHA-256 Accelerator Test Vectors\n")
    f.write("# Generated by gen_vectors.py\n\n")

    # NIST / spec vectors
    write_vector(f, "empty", b"", mode=1)
    write_vector(f, "abc",   b"abc", mode=1)
    write_vector(f, "55a",   b"a"*55, mode=1)
    write_vector(f, "56a",   b"a"*56, mode=1)
    write_vector(f, "63a",   b"a"*63, mode=1)
    write_vector(f, "64a",   b"a"*64, mode=1)
    write_vector(f, "119a",  b"a"*119, mode=1)
    write_vector(f, "120a",  b"a"*120, mode=1)
    write_vector(f, "nist_56b", b"abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq", mode=1)
    write_vector(f, "nist_112b", b"abcdefghbcdefghicdefghijdefghijkefghijklfghijklmghijklmnhijklmnoijklmnopjklmnopqklmnopqrlmnopqrsmnopqrstnopqrstu", mode=1)

    # Mode 0 versions of above
    write_vector(f, "abc_m0",   b"abc", mode=0)
    write_vector(f, "empty_m0", b"",    mode=0)

    # Random vectors
    rng = random.Random(42)
    for length in [0, 1, 55, 56, 57, 63, 64, 65, 119, 120, 127, 128, 200, 300, 400]:
        msg = bytes(rng.randint(0, 255) for _ in range(length))
        write_vector(f, f"rand_{length}", msg, mode=1)
        write_vector(f, f"rand_{length}_m0", msg, mode=0)

print(f"Generated: {os.path.join(OUT_DIR, 'vectors.hex')}")

# Also write a simple Python-readable format for simulation use
import json
vectors = {}
test_cases = [
    ("empty", b""),
    ("abc",   b"abc"),
    ("55a",   b"a"*55),
    ("56a",   b"a"*56),
    ("63a",   b"a"*63),
    ("64a",   b"a"*64),
    ("119a",  b"a"*119),
    ("120a",  b"a"*120),
    ("nist_56b", b"abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq"),
    ("nist_112b", b"abcdefghbcdefghicdefghijdefghijkefghijklfghijklmghijklmnhijklmnoijklmnopjklmnopqklmnopqrlmnopqrsmnopqrstnopqrstu"),
]
for name, msg in test_cases:
    vectors[name] = {
        "msg_hex": msg.hex(),
        "digest":  sha256hex(msg),
        "len":     len(msg)
    }

with open(os.path.join(OUT_DIR, 'vectors.json'), 'w') as f:
    json.dump(vectors, f, indent=2)

print(f"Generated: {os.path.join(OUT_DIR, 'vectors.json')}")
print("All vector digest lengths = 64 chars: OK")
